[package]
name = "libbackend"
version = "0.1.0"
authors = ["Michal Turek"]
edition = "2018"

[dependencies]
chrono = "~0.4"
failure = "~0.1"
fern = "~0.5"
log = "~0.4"
serde = { version = "~1", features = ["derive"] }

