[package]
name = "pakr"
version = "0.1.0"
authors = ["Michal Turek"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "~0.4"
failure = "~0.1"
fern = "~0.5"
log = "~0.4"
