version: '3'
services:
  postgres:
    image: "postgres:12.1"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pakr
      POSTGRES_PASSWORD: "**********"
      POSTGRES_DB: pakr
    shm_size: 256M
