logging:
  # Default logging level if a concrete module is not specified.
  default_level: debug

  # Optional: Log level per module.
  # modules:
     # pakr: debug
     # libbackend: debug
     # libbackend::logging: debug

server:
  # e.g. "127.0.0.1", "0.0.0.0", "[::1]"
  listen_address: "[::1]"
  listen_port: 3030
